### ISSUE TITLE
Raspberry Pi / ARMv7

### ISSUE THREAD

**Issue by howitzer-industries** [envkey/envkey-source#1]
Hey Dan, would it be possible to get a binary that will run on a Raspberry Pi?

```
$ uname -s
Linux
$ uname -m
armv7l
$ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
```

**Comment by danenania** [comment]
@howitzer-industries This should be working now, but I don't have a Raspberry Pi to test on, so let me know.
