### ISSUE TITLE
Honor *nix system proxy env vars

### ISSUE THREAD

**Issue by inhumantsar** [envkey/envkey-source#13]
We'd like to use envkey behind a few layers of corporate firewall. We have an HTTP(S) proxy we can use, but envkey seems to ignore the `http_proxy` and `https_proxy` env vars, and there doesn't seem to be a way to manually configure proxies for envkey. 

Am I missing something or is this a feature request?

**Comment by danenania** [comment]
Golang's http client normally respects these, but it's being initialized in a way that doesn't pass these through. It looks like it should be a pretty quick fix, so we'll try to get a new version released up soon with proxy support--stay tuned.

**Comment by danenania** [comment]
Ok, this should be fixed in 1.2.9
