### ISSUE TITLE
Add a homebrew tap

### ISSUE THREAD

**Issue by garbetjie** [envkey/envkey-source#15]
I see that this has been raised in #3 previously.

However, Homebrew allows custom repositories (taps) that are outside of the core of Homebrew. Could we perhaps look at creating a Homebrew tap for EnvKey?

I've created a working tap at https://github.com/garbetjie/homebrew-envkey, which could be used as the starting point? I would be happy to maintain this - but I feel like it would be more "official" coming from EnvKey?

**Comment by danenania** [comment]
Thanks for the prod on this @garbetjie!  Yes, we can add it under the official account and add you as a maintainer. I appreciate it!

To make sure I'm understanding correctly on versioning, it looks like the version can be inferred from the `url` field of the repo? So on a new release, we'd just need to update that field to point at the latest release?

**Comment by danenania** [comment]
Ok, the repo is here https://github.com/envkey/homebrew-envkey and homebrew installation instructions have been added to the README for envkey-source and envkey-fetch. It seems to be working well, but let me know if anything looks amiss. Thanks again!
