### ISSUE TITLE
variables with '.' fail to export

### ISSUE THREAD

**Issue by mackoftrack** [envkey/envkey-source#16]
If I have a variable like `api.access.token` it fails to load, causing the following error:

```
bash-4.4# eval $(envkey-source)
bash: export: `api.access.token=xxxxxxxxx': not a valid identifier
```

**Comment by danenania** [comment]
Hi! This an issue with environment variable names in the shell, which allow
only a limited set of characters:

From this SO answer:
https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

*Environment variable names used by the utilities in the Shell and
Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase
letters, digits, and the '_' (underscore)* from the characters defined in
Portable Character Set *and do not begin with a digit*. Other characters
may be permitted by an implementation; applications shall tolerate the
presence of such names.

While EnvKey should possibly block these ’invalid’ variable names, they’re
only an issue if you use envkey-source in the shell—using them with the
language-specific libs isn’t an issue, so we’ve decided to leave it up to
the user. We should definitely add a note on this in docs though.

**Comment by mackoftrack** [comment]
Thanks. This is a bummer, since all of our java applications' properties have dots in them 
i.e. `db.user` , `db.password` , and the environment variables override these. I'm not sure yet how we will be able to work around this apart from changing all of the property names we expect to pull from envkey. Any ideas?

**Comment by mackoftrack** [comment]
Perhaps I could try something like https://github.com/rmannibucau/envkey-client ?

**Comment by danenania** [comment]
That library was built for a very early beta version of EnvKey and is no longer compatible, so that's a no go, but what you could potentially do is call out to [envkey-fetch](https://github.com/envkey/envkey-fetch) from your Java app--envkey-fetch simply takes an `ENVKEY` and returns your config as json, so you wouldn't run into the invalid characters issue and you can do whatever you need to with the json. It's not quite as convenient as envkey-source, but should still be fairly simple. Would that work?

**Comment by mackoftrack** [comment]
Thanks, I will look into it.

**Comment by mackoftrack** [comment]
It would be really cool if there was an official integration for java :)

**Comment by danenania** [comment]
Agreed! It’s definitely on the roadmap. We’re a bit backed up with getting
our big v2 release out, but adding more languages (especially java) will be
the priority immediately after that.
