### ISSUE TITLE
failing to install

### ISSUE THREAD

**Issue by Casyfill** [envkey/envkey-source#17]
getting this on installation:
```
main.go:24:2: cannot find module providing package github.com/envkey/envkey-source/cmd: working directory is not part of a module
```

same both for `brew install envkey-source` (after tap) and `brew install envkey/envkey/envkey-source`

**Comment by danenania** [comment]
Thanks @Casyfill, looking into this. In the meantime you could try the curl/bash install if you're ok with that:

```
curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash
```
