### ISSUE TITLE
unable to fetch envkey in kubernetes version 1.15.10

### ISSUE THREAD

**Issue by SinghDivneet** [envkey/envkey-source#18]
This happens very intermittently where the like 10% of the pods start failing and we  get the following error`Get https://me66hg5t17.execute-api.eu-west-1.amazonaws.com/default/envBackup?v=1&id=********&clientName=envkey-source&clientVersion=1.2.9&clientOs=linux&clientArch=amd64: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) `. 

This works the rest 90% of the time.
we use the k8's secret manager to store the credentials

**Comment by danenania** [comment]
Hi! Thanks for reporting this. Not to pass the buck, but my first thought
is this might be a networking issue on your side, as we are not seeing any
errors on our end either from live requests or our monitoring. Are you
doing anything fancy in terms of networking/vpcs that could cause issues
with outgoing requests? Can you check whether https://env.envkey.com/health
can be reached on a pod that is having this problem?

**Comment by danenania** [comment]
@SinghDivneet Are you still having issues? Closing this for now.
