### ISSUE TITLE
Unable to install envkey-source on build server

### ISSUE THREAD

**Issue by roberthunterjr** [envkey/envkey-source#7]
I was previously able to install envkey on my build server using the following command:

`curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | sudo bash`

Now our team is receiving the following on execution:

```envkey-source 1.1.6 Quick Install
Copyright (c) 2017 Envkey Inc. - MIT License
https://github.com/envkey/envkey-source

Downloading envkey-source binary for linux-amd64
Downloading tarball from https://raw.githubusercontent.com/envkey/envkey-source/master/dist/envkey-source_1.1.6_linux_amd64.tar.gz
mv: cannot stat ‘envkey-source’: No such file or directory
envkey-source is installed in /usr/local/bin
Installation complete. Info:

bash: line 97: envkey-source: command not found
```

It appears that the address for grabbing the tarball is currently throwing a 404 error so I'm pretty sure thats the culprit. Not sure if it is temporary or if the address needs to be updated in the build script.

This is running on CircleCI docker machine using the circleci/node:8.11 image

**Comment by danenania** [comment]
Apologies - this was broken in the latest commit. The `dist` folder was removed from the repo to reduce file size, but I had forgotten that the install script points directly at the `dist` folder in master, not at the release. I'll rollback for now and then update the install script.

**Comment by roberthunterjr** [comment]
Sounds great. Thank you!

**Comment by danenania** [comment]
@roberthunterjr This should now be fixed.

**Comment by roberthunterjr** [comment]
Yes, this is fixed now. Thank you

**Comment by franciscomerdot** [comment]
@danenania because of this fix, our Heroku Build Pack now it's broken, can you update the script `compile` script to point to the right versioned file?

**Comment by danenania** [comment]
@franciscomerdot sorry about that - updating now.

**Comment by danenania** [comment]
@franciscomerdot it should now be fixed.

**Comment by franciscomerdot** [comment]
@danenania Yes, it works now, thanks.

**Comment by JacobDel** [comment]
It seems the issue still persists:
```
user@Users-MacBook-Pro Desktop % curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash     
envkey-source 1.2.10 Quick Install
Copyright (c) 2021 Envkey Inc. - MIT License
https://github.com/envkey/envkey-source

Downloading envkey-source binary for darwin-arm64
Downloading tarball from Github Releases: https://github.com/envkey/envkey-source/releases/download/v1.2.10/envkey-source_1.2.10_darwin_arm64.tar.gz
mv: rename envkey-source to /usr/local/bin/envkey-source: Permission denied
envkey-source is installed in /usr/local/bin
Installation complete. Info:

bash: line 107: envkey-source: command not found
```
