### ISSUE TITLE
Linux VM installation bug

### ISSUE THREAD

**Issue by GregTheGreek** [envkey/envkey-source#8]
Hey Dane,

Found some weird behaviour on two of our servers:
OS: Ubuntu 16.04 LTS
Host: Azure & GCP

When installing the env-source you must be in the root directory  (`$ cd`) for the logged in user otherwise it installs incorrectly.

output:
```
<server> $ curl -s https://raw.githubusercontent.com/envkey/envkey-source/master/install.sh | bash
cat: .ek_tmp_version: No such file or directory
rm: cannot remove '.ek_tmp_version': No such file or directory
envkey-source  Quick Install
Copyright (c) 2017 Envkey Inc. - MIT License
https://github.com/envkey/envkey-source

Downloading envkey-source binary for linux-amd64
Downloading tarball from https://github.com/envkey/envkey-source/releases/download/v/envkey-source__linux_amd64.tar.gz
mv: cannot stat 'envkey-source': No such file or directory
envkey-source is installed in /usr/local/bin
rm: cannot remove 'envkey-source.tar.gz': No such file or directory
Installation complete. Info:

bash: line 97: envkey-source: command not found

<server>: $ eval $(envkey-source)
envkey-source: command not found
```

**Comment by GregTheGreek** [comment]
When i run that i get no output. But there is no failure either.
`sudo curl -s -o .ek_tmp_version https://raw.githubusercontent.com/envkey/envkey-source/master/version.txt`

**Comment by danenania** [comment]
Ok, I'll do some investigation on Ubuntu 16.04 - perhaps it makes sense to just write the temp files to $HOME to be safe.

**Comment by danenania** [comment]
@GregTheGreek Added a note on this to the README.
